name: Rust

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*-linux'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare for build
      run: |
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v3
    - name: Initialize submodule
      run: |
        git submodule init
        git submodule update
    - name: Install AMD HIP SDK
      run: |
        sudo apt update
        wget https://repo.radeon.com/amdgpu-install/5.7.1/ubuntu/jammy/amdgpu-install_5.7.50701-1_all.deb
        sudo apt install ./amdgpu-install_5.7.50701-1_all.deb
        sudo apt update
        sudo amdgpu-install --usecase=rocm,hip,hiplibsdk
    - name: Build for Linux
      run: |
        cargo xtask --release
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          This release is automatically generated by GitHub Actions and not tested.
        draft: false
        prerelease: true

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build for Windows
      run: |
        git submodule init
        git submodule update
        C:\msys64\usr\bin\wget.exe https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q4-Win10-Win11-For-HIP.exe -O "amdgpu-install.exe"
        .\amdgpu-install.exe -Install
        cargo xtask --release
