name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build for Linux
      run: |
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        git submodule init
        git submodule update
        sudo apt update
        wget https://repo.radeon.com/amdgpu-install/5.7.1/ubuntu/jammy/amdgpu-install_5.7.50701-1_all.deb
        sudo apt install ./amdgpu-install_5.7.50701-1_all.deb
        sudo apt update
        sudo amdgpu-install --usecase=rocm,hip,hiplibsdk
        cargo xtask --release

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build for Windows
      run: |
        git submodule init
        git submodule update
        wget https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-23.Q4-Win10-Win11-For-HIP.exe -OutFile "amdgpu-install.exe"
        .\amdgpu-install.exe -Install
        cargo xtask --release
